name: waka_time_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  http: ^0.13.4
  dartz: ^0.10.1

  fl_chart: ^0.50.6
  flutter_secure_storage: ^5.0.2
  auto_route: ^4.0.1
  url_launcher: ^6.1.2
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  lottie: ^1.3.0
  flutter_staggered_animations: 1.0.0
  collection: ^1.16.0

  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  meta: ^1.7.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  bloc_test: ^9.0.3

  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
  auto_route_generator: ^4.0.0
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/illustrations/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
